booleanito = True
while booleanito == True:
    print("______________________________________________________________________")
    print("                                                                      ")
    print("                 Bienvenido a la libreria de Personas                 ")
    print("______________________________________________________________________")
    print("                                                                      ")
    print("                 1. Crear Persona                                     ")
    print("                 2. Mostrar todas las personas                        ")
    print("                 3. Mostrar a una persona individual                  ")
    print("                 4. Actualizar a una persona en especifico            ")
    print("                 5. Eliminar a una persona en especifico              ")
    print("                 6. Cerrar Programa                                   ")
    print("______________________________________________________________________")
    seleccionUsuario = int(input(' '))
    if seleccionUsuario == 1:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                     Seleccionaste: Crear Persona                     ")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("             Ingresa el numero de personas que desea crear            ")
        print("______________________________________________________________________")
        limite = int(input(''))
        libreriaPersonas = []
        for i in range(1, limite + 1):
            persona = {}
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                       Ingresa id de la Persona:",i,"                 ")
            print("______________________________________________________________________")
            persona["id"] = int(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                   Ingresa el nombre de la Persona:",i,"              ")
            print("______________________________________________________________________")
            persona["nombre"] = str(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                  Ingresa el apellido de la Persona:",i,"             ")
            print("______________________________________________________________________")
            persona["apellido"] = str(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                    Ingresa la edad de la Persona:",i,"               ")
            print("______________________________________________________________________")
            persona["edad"] = int(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                          Persona Registrada                          ")
            print("______________________________________________________________________")
            libreriaPersonas.append(persona)
    elif seleccionUsuario == 2:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("               Seleccionaste: Mostrar todos los Usuarios              ")
        print("______________________________________________________________________")
        for i in range(len(libreriaPersonas)):
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                           Persona ",i+1,"                            ")
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                  id: ",libreriaPersonas[i]["id"],"                   ")
            print("              Nombre: ",libreriaPersonas[i]["nombre"],"               ")
            print("            Apellido: ",libreriaPersonas[i]["apellido"],"             ")
            print("                Edad: ",libreriaPersonas[i]["edad"],"                 ")
            print("______________________________________________________________________")
    elif seleccionUsuario == 3:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("            Seleccionaste: Mostrar a una persona individual           ")
        print("______________________________________________________________________")
        if len(libreriaPersonas) == 0:
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                     ¡NO HAY PERSONAS REGISTRADAS!                    ")
            print("______________________________________________________________________")
        else:
            print("______________________________________________________________________")
            print("                                                                      ")
            print("             Ingresa el ID de la persona que desea Mostrar            ")
            print("______________________________________________________________________")
            idPersona = int(input(" "))
            if persona["id"] == idPersona:
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                         Persona Encontrada                           ")
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                         Id:", persona["id"],"                        ")
                print("                     Nombre:", persona["nombre"],"                    ")
                print("                   Apellido:", persona["apellido"],"                  ")
                print("                       Edad:", persona["edad"],"                      ")
                print("______________________________________________________________________")
    elif seleccionUsuario == 6: 
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                   Seleccionaste: Cerrar el programa                  ")
        print("______________________________________________________________________")
        booleanito = False
    else: 
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                       ¡Ingresa un numero Valido!                     ")
        print("______________________________________________________________________")

# Desarrollado por Gustavo Adolfo Navarro Pacheco T.I 1.127.599.969