booleanito = True
libreriaPersonas = []
while booleanito == True:
    print("______________________________________________________________________")
    print("                                                                      ")
    print("                 Bienvenido a la libreria de Personas                 ")
    print("______________________________________________________________________")
    print("                                                                      ")
    print("                 1. Crear Persona                                     ")
    print("                 2. Mostrar todas las personas                        ")
    print("                 3. Mostrar a una persona individual                  ")
    print("                 4. Actualizar a una persona en especifico            ")
    print("                 5. Eliminar a una persona en especifico              ")
    print("                 6. Cerrar Programa                                   ")
    print("______________________________________________________________________")
    seleccionUsuario = int(input(' '))
    if seleccionUsuario == 1:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                     Seleccionaste: Crear Persona                     ")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("             Ingresa el numero de personas que desea crear            ")
        print("______________________________________________________________________")
        limite = int(input(''))
        for i in range(1, limite + 1):
            persona = {}
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                       Ingresa id de la Persona:",i,"                 ")
            print("______________________________________________________________________")
            persona["id"] = int(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                   Ingresa el nombre de la Persona:",i,"              ")
            print("______________________________________________________________________")
            persona["nombre"] = str(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                  Ingresa el apellido de la Persona:",i,"             ")
            print("______________________________________________________________________")
            persona["apellido"] = str(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                    Ingresa la edad de la Persona:",i,"               ")
            print("______________________________________________________________________")
            persona["edad"] = int(input(" "))
            print("______________________________________________________________________")
            print("                                                                      ")
            print("           Ingresa la cantidad de numeros que desea agregar           ")
            print("______________________________________________________________________")
            limiteNumeros = int(input(" "))
            for n in range(limiteNumeros):
                numero = {}
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                  Tipo de Numero (Trabajo/Personal):",n,"             ")
                print("______________________________________________________________________")
                numero["tipo"] = str(input(" "))
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                              Codigo:",n,"                            ")
                print("______________________________________________________________________")
                numero["codigo"] = int(input(" "))
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                              Numero:",n,"                            ")
                print("______________________________________________________________________")
                numero["numero"] = int(input(" "))
                persona["numero"].append(numero)
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                          Persona Registrada                          ")
            print("______________________________________________________________________")
            libreriaPersonas.append(persona)
    elif seleccionUsuario == 2:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("               Seleccionaste: Mostrar todos los Usuarios              ")
        print("______________________________________________________________________")
        for i in range(len(libreriaPersonas)):
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                           Persona ",i+1,"                            ")
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                  id: ",libreriaPersonas[i]["id"],"                   ")
            print("              Nombre: ",libreriaPersonas[i]["nombre"],"               ")
            print("            Apellido: ",libreriaPersonas[i]["apellido"],"             ")
            print("                Edad: ",libreriaPersonas[i]["edad"],"                 ")
            print("______________________________________________________________________")
            print(limiteNumeros)
            for n in range(len(persona["numeros"])):
                numero = persona["numeros"][n]
                print("______________________________________________________________________")
                print("                                                                      ")
                print("               Número", n + 1, "de", len(persona["numeros"]), "de", persona["nombre"])
                print("______________________________________________________________________")
                print("     Tipo de Número (Trabajo/Personal):",numero[n]["tipo"])
                print("                           Código:",numero[n]["codigo"])
                print("                           Número:",numero[n]["numero"])
                print("______________________________________________________________________")
    elif seleccionUsuario == 3:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("            Seleccionaste: Mostrar a una persona individual           ")
        print("______________________________________________________________________")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("             Ingresa el ID de la persona que desea Mostrar            ")
        print("______________________________________________________________________")
        idPersona = int(input(" "))
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                         Persona ID:",idPersona,"                     ")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                    Id:",libreriaPersonas[idPersona-1]["id"],"        ")
        print("                Nombre:",libreriaPersonas[idPersona-1]["nombre"],"    ")
        print("              Apellido:",libreriaPersonas[idPersona-1]["apellido"],"  ")
        print("                  Edad:",libreriaPersonas[idPersona-1]["edad"],"      ")
        print("______________________________________________________________________")
        for n in range(len(persona["numeros"])):
                numero = persona["numeros"][n]
                print("______________________________________________________________________")
                print("                                                                      ")
                print("               Número", n + 1, "de", len(persona["numeros"]), "de", persona["nombre"])
                print("______________________________________________________________________")
                print("     Tipo de Número (Trabajo/Personal):",numero[n]["tipo"])
                print("                           Código:",numero[n]["codigo"])
                print("                           Número:",numero[n]["numero"])
                print("______________________________________________________________________")
    elif seleccionUsuario == 4:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("         Seleccionaste: Actualizar a una persona en Especifico        ")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("            Ingresa el ID de la persona que desea Actualizar          ")
        print("______________________________________________________________________")
        idPersona = int(input(" "))
        for persona in libreriaPersonas:
            if persona["id"] == idPersona:
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                       Id:",persona["id"],"                           ")
                print("                   Nombre:",persona["nombre"],"                       ")
                print("                 Apellido:",persona["apellido"],"                     ")
                print("                     Edad:",persona["edad"],"                         ")
                print("______________________________________________________________________")
                for i in range(len(persona["numeros"])):
                    print("______________________________________________________________________")
                    print("               Número", i + 1)
                    print("     Tipo:",persona["numeros"][i]["tipo"])
                    print("   Código:",persona["numeros"][i]["codigo"])
                    print("   Número:",persona["numeros"][i]["numero"])
                    print("______________________________________________________________________")
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                       Ingresa el nuevo nombre                        ")
                print("______________________________________________________________________")
                persona["nombre"] = input(" ")
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                      Ingresa el nuevo apellido                       ")
                print("______________________________________________________________________")
                persona["apellido"] = input(" ")
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                        Ingresa la nueva edad                         ")
                print("______________________________________________________________________")
                persona["edad"] = int(input(" "))
                for i in range(len(persona["numeros"])):
                    print("______________________________________________________________________")
                    print("                                                                      ")
                    print("               Ingresa el nuevo tipo (Trabajo/Personal):              ")
                    print("______________________________________________________________________")
                    persona["numeros"][i]["tipo"] = input(" ")
                    print("______________________________________________________________________")
                    print("                                                                      ")
                    print("                       Ingresa el nuevo Codigo:                       ")
                    print("______________________________________________________________________")
                    persona["numeros"][i]["codigo"] = input(" ")
                    print("______________________________________________________________________")
                    print("                                                                      ")
                    print("                       Ingresa el nuevo numero:                       ")
                    print("______________________________________________________________________")
                    persona["numeros"][i]["numero"] = input(" ")
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                         Persona actualizada                          ")
                print("______________________________________________________________________")
                break
            else:
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                           ID No encontrado                           ")
                print("______________________________________________________________________")
    elif seleccionUsuario == 5:
        print("______________________________________________________________________")
        print("                                                                      ")
        print("            Seleccionaste: Eliminar Usuario en Especifico             ")
        print("______________________________________________________________________")
        print("                                                                      ")
        print("             Ingresa el ID de la persona que deseas eliminar          ")
        print("______________________________________________________________________")
        idPersona = int(input("ID: "))
        for i in range(len(libreriaPersonas)):
            if libreriaPersonas[i]["id"] == idPersona:
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                    Id:",libreriaPersonas[i]["id"],"                  ")
                print("                Nombre:",libreriaPersonas[i]["nombre"],"              ")
                print("              Apellido:",libreriaPersonas[i]["apellido"],"            ")
                print("                  Edad:",libreriaPersonas[i]["edad"],"                ")
                print("______________________________________________________________________")
                for n in range(len(libreriaPersonas[i]["numeros"])):
                    print("______________________________________________________________________")
                    print("                                                                      ")
                    print("                           Número",n + 1,"                            ")
                    print("     Tipo:",libreriaPersonas[i]["numeros"][n]["tipo"],"               ")
                    print("   Código:",libreriaPersonas[i]["numeros"][n]["codigo"],"             ")
                    print("   Número:",libreriaPersonas[i]["numeros"][n]["numero"],"             ")
                    print("______________________________________________________________________")
                del libreriaPersonas[i]
                print("______________________________________________________________________")
                print("                                                                      ")
                print("                   Usuario eliminado correctamente                    ")
                print("______________________________________________________________________")
        else:
            print("______________________________________________________________________")
            print("                                                                      ")
            print("                           ID no encontrado                           ")
            print("______________________________________________________________________")
    elif seleccionUsuario == 6: 
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                   Seleccionaste: Cerrar el programa                  ")
        print("______________________________________________________________________")
        booleanito = False
    else: 
        print("______________________________________________________________________")
        print("                                                                      ")
        print("                       ¡Ingresa un numero Valido!                     ")
        print("______________________________________________________________________")

# Desarrollado por Gustavo Adolfo Navarro Pacheco T.I 1.127.599.969